---
title: "Qfish"
author: "Patience"
date: "2025-04-09"
output: html_document
---

# To download data go to:
https://qfish.fisheries.qld.gov.au/query/charter-catch-and-effort/table


# Research Question
What is the relationship between the number of diving licences and the number of days at sea?


# Packages
```{r, warning=FALSE, message=FALSE}
library(janitor)
library(tidyverse)
```


# Load data
```{r, warning=FALSE, message=FALSE}
DataQ <- 
  read.csv("../RData/Data Qfish.csv") |>
  row_to_names(row_number = 1) |> # Variable names are meaningless, so remove
  clean_names() # But we want 
```

# Clean data
```{r, warning=FALSE, message=FALSE}
diving <- DataQ |>
  select(x | contains("diving")) |>
  row_to_names(row_number = 1) |>
  mutate(across(is.character, as.numeric)) |>
  filter(!is.na(CalendarYear))
```


# Data exploration
```{r}
diving_clean <- diving %>% filter (!is.na(Licences), !is.na(Days))
```

# plot Graph


```{r}
diving_no_outliers <- diving_clean %>%
  filter(Days <= 220)
```

```{r}
ggplot(diving_no_outliers, aes(x = Licences, y = Days)) +
  geom_point(aes(color = Days, size = Licences), alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, color = "black", linetype = "dashed") +
  scale_color_viridis_c() +
  labs(title = "Relationship Between Diving Licences and Days at Sea",
       
       x = "Number of Licences",
       y = "Days at Sea",
       color = "Days",
       size = "Licences") +
  theme_minimal(base_size = 10) +
  theme(legend.position = "bottom")
```

